blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: 'https://github.com/Caio-Freitas005/insectapi/discussions/new?category=q-a'
    about: Ask a general question about the project using discussions